## The following code is used to find the matrix inversion .
## Matrix inversion is usually costly computation in terms of time taken to compute the result,
## The following code ,overcomes the above said problem ,by .........
##            ...........caching the matrix inversion rather than compute it repeatedly. 
##initially 'x' is assigned a list of elements.
## then itis converted to matrix.

## the function 'makeCacheMatrix' takes 'x' as input ,which is of class 'matrix' 
## this function takes input and also stores and display  the  inverse of the given matrix ,which is 
##    generated by  'cacheSolve()' function
## 
## 



makeCacheMatrix <- function(x = matrix()) {                             ## 'x'is the matrix() 

        dim(x)<-c(2,2)                                                  ## 'x' is converted to matrix
        i<- NULL                                                        ## inverse of matrix is set to NULL


    set <- function(y)                                                  ##takes the fresh input from user
            {                                                           ## sets the new input to 'x'
                dim(y)<-c(2,2)
                x <<- y
               
                i <<- NULL
            }
     
    get <- function()                                                   ## displays the value of the input 'x'                
            {
              x
            }
    
    setinverse <- function(inv)                                         ##stores the inverse of matrix value
            { 
              i <<- inv
            }   
  
    getinverse <- function()                                            ## displays the inverse of  matrix
            {
               i
            }   
    
    list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)

}


## Write a short comment describing this function
The
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        
      i <- x$getinverse()
  if(!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data)
  x$setinverse(i)
  i  
}
