## The following code is used to find the matrix inversion .
## Matrix inversion is usually costly computation in terms of time taken to compute the result,
## The following code ,overcomes the above said problem ,by .........
##            ...........caching the matrix inversion rather than compute it repeatedly. 
##initially 'x' is assigned a list of elements.
## then it is converted to matrix.

## the function 'makeCacheMatrix' takes 'x' as input ,which is of class 'matrix' 
## this function takes input and also stores and display  the  inverse of the given matrix ,which is 
##    generated by  'cacheSolve()' function




makeCacheMatrix <- function(x = matrix())                               ## 'x'is the matrix() 
{                             

        dim(x)<-c(2,2)                                                  ## 'x' is converted to matrix
        i<- NULL                                                        ## inverse of matrix is set to NULL


    set <- function(y)                                                  ##takes the fresh input from user
            {                                                           ## sets the new input to 'x'
                dim(y)<-c(2,2)
                x <<- y
               
                i <<- NULL
            }
     
    get <- function()                                                   ## displays the value of the input 'x'                
            {
              x
            }
    
    setinverse <- function(inv)                                         ##stores the inverse of matrix value
            { 
              i <<- inv
            }   
  
    getinverse <- function()                                            ## displays the inverse of  matrix
            {
               i
            }   
    
    list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)

}


## This function calculates the inverse of the given matrix ,if not already present in the 'makeCacheMatrix'.

cacheSolve <- function(x, ...)

{
        ## Return a matrix that is the inverse of 'x'
        
         i <- x$getinverse()                                            ## look for inverse in the  'makeCacheMatrix'  
         
         if(!is.null(i))                                                ## if inverse is not null      
            {
                 message("getting cached data")                         ## display the message 
                 return(i)                                              ## return the inverse        
            }
         
         ## otherwise,if reverse is not already calculated and is stored in the makeCacheMatrix,then  
         
         data <- x$get()                                                ## get the matrix and put into a variable 'data'                                                
         i <- solve(data)                                               ## 'solve' finction finds inverse of the given matrix
         x$setinverse(i)                                                ## this inverse value is stored into makeCacheMatrix function        
         i                                                              ## displays the inverse of the matrix        
}
